import pygame

SCREEN_WIDTH = 400
SCREEN_HEIGHT = 400
SCREEN = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
TILE_WIDTH = 40
TILE_HEIGHT = 40
COLUMNS  = SCREEN_WIDTH // TILE_WIDTH
ROWS = SCREEN_HEIGHT // TILE_HEIGHT
LINE_COLOR = (30, 200, 30)
VISITED_COLOR = (0, 100, 0)