import pygame

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600
SCREEN = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
TILE_WIDTH = 20
TILE_HEIGHT = 20
COLUMNS  = SCREEN_WIDTH // TILE_WIDTH
ROWS = SCREEN_HEIGHT // TILE_HEIGHT
LINE_COLOR = (0, 0, 0)
VISITED_COLOR = (50, 100, 50)
UNVISITED_COLOR = (0, 100, 0)